from pathlib import Path
SCRIPT_DIR=Path(__file__).resolve().parent
PROJECT_ROOT=SCRIPT_DIR.parent
B2C1_DIR=PROJECT_ROOT/"step04B2C1_uvi_gamma_uo3_screen"
EXP_PRIM=B2C1_DIR/"estruturas"/"gamma_UO3_293K_primitive.traj"
EXP_MANIFEST=B2C1_DIR/"estruturas"/"gamma_UO3_structure_manifest.json"
MATRIX_DIR=PROJECT_ROOT/"step03_paw_pbesol_benchmark"/"paw_generated"/"PBEsol"
U_DIR=PROJECT_ROOT/"step04_u_pb_paw_validation"/"paw_candidates"/"U_R5_pseudization"/"U14_nc6"/"PBEsol"
RESULTS=SCRIPT_DIR/"resultados_step04B2C2"
LOGS=SCRIPT_DIR/"logs"
RELAX=RESULTS/"relax"
GPW=RESULTS/"gpw"
XC="PBEsol"; UEFF_EV=3.0; ECUT_PROD_EV=1600.0; ECUT_VAL_EV=1800.0
KPTS_PROD=(2,2,2); KPTS_VAL=(3,3,3)
NBANDS_RELAX=160; NBANDS_FINAL=192; SMEARING_EV=0.05
EXP_A_A=9.787; EXP_B_A=19.932; EXP_C_A=9.705
EXP_VOLUME_A3=EXP_A_A*EXP_B_A*EXP_C_A
EXP_SPACEGROUP=70; EXP_SHORTEST_UO_A=1.796; EXP_GAP_GUIDE_EV=2.38
SYMPREC_RELAX_A=0.01
ATOM_FMAX_STAGE1_EV_A=0.03; COUPLED_FMAX_STAGE1_EV_A=0.03
ATOM_FMAX_STAGE2_EV_A=0.015; COUPLED_FMAX_FINAL_EV_A=0.015
MAX_LATTICE_ERROR_PERCENT=2.0; MAX_VOLUME_ERROR_PERCENT=4.0
MAX_SHORTEST_UO_ERROR_PERCENT=5.0; MAX_UO6_RMS_REL_ERROR_PERCENT=3.0
MAX_FINAL_FORCE_EV_A=0.05; MAX_FINAL_STRESS_GPA=0.40
MAX_DENERGY_MEV_ATOM=2.0; MAX_DGAP_EV=0.08; MAX_DSTRESS_GPA=0.20
MAX_SOC_SCALE0_VS_SCALAR_GAP_EV=0.05
MAX_SOC_SUBSPACE_DGAP_EV=0.05; MAX_SOC_KPOINT_DGAP_EV=0.10
MAX_SOC_CUTOFF_DGAP_EV=0.08
MIN_FINAL_SOC_GAP_EV=1.2; MAX_FINAL_SOC_GAP_EV=3.2
